// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OAuthServer.Data;

#nullable disable

namespace OAuthServer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124202230_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OAuthServer.Core.Models.DeckVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListeningCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningCategoryId");

                    b.ToTable("DeckVideo");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.DeckWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlashcardCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardCategoryId");

                    b.ToTable("DeckWord");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PracticeId");

                    b.HasIndex("UserId");

                    b.ToTable("Flashcard");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.FlashcardCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlashcardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardId");

                    b.ToTable("FlashcardCategory");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.FlashcardOldSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("FlashcardCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FlashcardId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardCategoryId");

                    b.HasIndex("FlashcardId");

                    b.ToTable("FlashcardOldSession");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.FlashcardSessionRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlashcardOldSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardOldSessionId");

                    b.ToTable("FlashcardSessionRow");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Listening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PracticeId");

                    b.HasIndex("UserId");

                    b.ToTable("Listening");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ListeningCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ListeningId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningId");

                    b.ToTable("ListeningCategory");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ListeningOldSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ListeningCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ListeningId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningCategoryId");

                    b.HasIndex("ListeningId");

                    b.ToTable("ListeningOldSession");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ListeningSessionRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListenedSentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListeningOldSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Similarity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningOldSessionId");

                    b.ToTable("ListeningSessionRow");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Practice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Practice");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PracticeId");

                    b.HasIndex("UserId");

                    b.ToTable("Reading");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ReadingBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeftColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReadingId")
                        .HasColumnType("int");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReadingId");

                    b.ToTable("ReadingBook");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ReadingOldSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReadingBookId")
                        .HasColumnType("int");

                    b.Property<int>("ReadingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReadingBookId");

                    b.HasIndex("ReadingId");

                    b.ToTable("ReadingOldSession");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ReadingSessionRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnswerTranslate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReadingOldSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SelectedSentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Similarity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReadingOldSessionId");

                    b.ToTable("ReadingSessionRow");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("NativeLanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NativeLanguageId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OAuthServer.Core.Models.UserRefreshToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("UserRefreshToken");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Writing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PracticeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PracticeId");

                    b.HasIndex("UserId");

                    b.ToTable("Writing");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.WritingBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeftColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WritingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WritingId");

                    b.ToTable("WritingBook");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.WritingOldSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WritingBookId")
                        .HasColumnType("int");

                    b.Property<int>("WritingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WritingBookId");

                    b.HasIndex("WritingId");

                    b.ToTable("WritingOldSession");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.WritingSessionRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnswerTranslate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedSentence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Similarity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WritingOldSessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WritingOldSessionId");

                    b.ToTable("WritingSessionRow");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OAuthServer.Core.Models.DeckVideo", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.ListeningCategory", "ListeningCategory")
                        .WithMany("DeckVideos")
                        .HasForeignKey("ListeningCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListeningCategory");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.DeckWord", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.FlashcardCategory", "FlashcardCategory")
                        .WithMany("DeckWords")
                        .HasForeignKey("FlashcardCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardCategory");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Flashcard", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.Language", "Language")
                        .WithMany("Flashcards")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.Practice", "Practice")
                        .WithMany("Flashcards")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.User", "User")
                        .WithMany("Flashcards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Practice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.FlashcardCategory", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.Flashcard", "Flashcard")
                        .WithMany("FlashcardCategories")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.FlashcardOldSession", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.FlashcardCategory", "FlashcardCategory")
                        .WithMany("FlashcardOldSessions")
                        .HasForeignKey("FlashcardCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.Flashcard", "Flashcard")
                        .WithMany("FlashcardOldSessions")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("FlashcardCategory");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.FlashcardSessionRow", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.FlashcardOldSession", "FlashcardOldSession")
                        .WithMany("FlashcardSessionRows")
                        .HasForeignKey("FlashcardOldSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardOldSession");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Listening", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.Language", "Language")
                        .WithMany("Listenings")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.Practice", "Practice")
                        .WithMany("Listenings")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.User", "User")
                        .WithMany("Listenings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Practice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ListeningCategory", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.Listening", "Listening")
                        .WithMany("ListeningCategories")
                        .HasForeignKey("ListeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listening");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ListeningOldSession", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.ListeningCategory", "ListeningCategory")
                        .WithMany("ListeningOldSessions")
                        .HasForeignKey("ListeningCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.Listening", "Listening")
                        .WithMany("ListeningOldSessions")
                        .HasForeignKey("ListeningId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Listening");

                    b.Navigation("ListeningCategory");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ListeningSessionRow", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.ListeningOldSession", "ListeningOldSession")
                        .WithMany("ListeningSessionRows")
                        .HasForeignKey("ListeningOldSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListeningOldSession");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Practice", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.Language", "Language")
                        .WithMany("Practices")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Reading", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.Language", "Language")
                        .WithMany("Readings")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.Practice", "Practice")
                        .WithMany("Readings")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.User", "User")
                        .WithMany("Readings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Practice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ReadingBook", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.Reading", "Reading")
                        .WithMany("ReadingBooks")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ReadingOldSession", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.ReadingBook", "ReadingBook")
                        .WithMany("ReadingOldSessions")
                        .HasForeignKey("ReadingBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.Reading", "Reading")
                        .WithMany("ReadingOldSessions")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reading");

                    b.Navigation("ReadingBook");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ReadingSessionRow", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.ReadingOldSession", "ReadingOldSession")
                        .WithMany("ReadingSessionRows")
                        .HasForeignKey("ReadingOldSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingOldSession");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.User", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.Language", "Language")
                        .WithMany("Users")
                        .HasForeignKey("NativeLanguageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Language");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Writing", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.Language", "Language")
                        .WithMany("Writings")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.Practice", "Practice")
                        .WithMany("Writings")
                        .HasForeignKey("PracticeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.User", "User")
                        .WithMany("Writings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Practice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.WritingBook", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.Writing", "Writing")
                        .WithMany("WritingBooks")
                        .HasForeignKey("WritingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Writing");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.WritingOldSession", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.WritingBook", "WritingBook")
                        .WithMany("WritingOldSessions")
                        .HasForeignKey("WritingBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OAuthServer.Core.Models.Writing", "Writing")
                        .WithMany("WritingOldSessions")
                        .HasForeignKey("WritingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Writing");

                    b.Navigation("WritingBook");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.WritingSessionRow", b =>
                {
                    b.HasOne("OAuthServer.Core.Models.WritingOldSession", "WritingOldSession")
                        .WithMany("WritingSessionRows")
                        .HasForeignKey("WritingOldSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WritingOldSession");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Flashcard", b =>
                {
                    b.Navigation("FlashcardCategories");

                    b.Navigation("FlashcardOldSessions");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.FlashcardCategory", b =>
                {
                    b.Navigation("DeckWords");

                    b.Navigation("FlashcardOldSessions");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.FlashcardOldSession", b =>
                {
                    b.Navigation("FlashcardSessionRows");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Language", b =>
                {
                    b.Navigation("Flashcards");

                    b.Navigation("Listenings");

                    b.Navigation("Practices");

                    b.Navigation("Readings");

                    b.Navigation("Users");

                    b.Navigation("Writings");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Listening", b =>
                {
                    b.Navigation("ListeningCategories");

                    b.Navigation("ListeningOldSessions");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ListeningCategory", b =>
                {
                    b.Navigation("DeckVideos");

                    b.Navigation("ListeningOldSessions");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ListeningOldSession", b =>
                {
                    b.Navigation("ListeningSessionRows");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Practice", b =>
                {
                    b.Navigation("Flashcards");

                    b.Navigation("Listenings");

                    b.Navigation("Readings");

                    b.Navigation("Writings");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Reading", b =>
                {
                    b.Navigation("ReadingBooks");

                    b.Navigation("ReadingOldSessions");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ReadingBook", b =>
                {
                    b.Navigation("ReadingOldSessions");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.ReadingOldSession", b =>
                {
                    b.Navigation("ReadingSessionRows");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.User", b =>
                {
                    b.Navigation("Flashcards");

                    b.Navigation("Listenings");

                    b.Navigation("Readings");

                    b.Navigation("Writings");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.Writing", b =>
                {
                    b.Navigation("WritingBooks");

                    b.Navigation("WritingOldSessions");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.WritingBook", b =>
                {
                    b.Navigation("WritingOldSessions");
                });

            modelBuilder.Entity("OAuthServer.Core.Models.WritingOldSession", b =>
                {
                    b.Navigation("WritingSessionRows");
                });
#pragma warning restore 612, 618
        }
    }
}
