# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["OAuthServer.API/OAuthServer.API.csproj", "OAuthServer.API/"]
COPY ["OAuthServer.Service/OAuthServer.Service.csproj", "OAuthServer.Service/"]
COPY ["OAuthServer.Data/OAuthServer.Data.csproj", "OAuthServer.Data/"]
COPY ["OAuthServer.Core/OAuthServer.Core.csproj", "OAuthServer.Core/"]
RUN dotnet restore "./OAuthServer.API/OAuthServer.API.csproj"
COPY . .
WORKDIR "/src/OAuthServer.API"
RUN dotnet build "./OAuthServer.API.csproj" -c $BUILD_CONFIGURATION -o /app/build


# MIGRATION STAGE
FROM build AS migration
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"
WORKDIR /src
RUN dotnet build OAuthServer.API/OAuthServer.API.csproj -c Release
ENTRYPOINT ["dotnet", "ef", "database", "update", \
            "--project", "OAuthServer.Data/OAuthServer.Data.csproj", \
            "--startup-project", "OAuthServer.API/OAuthServer.API.csproj", \ 
            "--no-build", \
            "--configuration", "Release"]


# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./OAuthServer.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app

# CURL INSTALLATION FOR HEALTH CHECKS
USER root
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
USER $APP_UID


COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OAuthServer.API.dll"]