using OAuthServer.Core.DTOs;
using OAuthServer.Core.Helper;

namespace OAuthServer.Core.Services;

public interface IUserService
{
    // BURDA BULUNAN METOTLARIN IMPLAMENTASYONU SERVICE KATMANINDA YAPILIR.
    // BURADA BULUNAN METOTLAR SERVICE VEYA PRESENTATION (API) KATMANINDA KULLANILABİLİR.
    // METOTLARDAN DÖNEN VERİ İSE SERVICE VEYA PRESENTATION (API) KATMANINDA KULLANILABİLİR.

    Task<Response<UserDto>> CreateUserAsync(SignUpDto signUpDto);
}